package shmacronym

var Adjectives = map[rune][]string{
	'a': {"abstract"},
	'b': {"binding"},
	'c': {"code"},
	'd': {"distributed"},
	'e': {"embedded", "extensible"},
	'f': {"fallback"},
	'g': {"generic"},
	'h': {"hyper"},
	'i': {"idempotent"},
	'j': {"joint"},
	'k': {"kubernetes"},
	'l': {"ledger"},
	'm': {"management"},
	'n': {"network"},
	'o': {"open"},
	'p': {"permissive"},
	'q': {"quantum"},
	'r': {"reachable"},
	's': {"streaming"},
	't': {"tenant"},
	'u': {"unit"},
	'v': {"virtual"},
	'w': {"wrapper"},
	'x': {"xtensible"},
	'y': {"yield"},
	'z': {"zorc"},
}

var Nouns = map[rune][]string{
	'a': {"abstract"},
	'b': {"business"},
	'c': {"code"},
	'd': {"distributed"},
	'e': {"embedded", "extensible"},
	'f': {"fallback"},
	'g': {"generic"},
	'h': {"hyperledger"},
	'i': {"idempotent"},
	'j': {"join"},
	'k': {"kubernetes"},
	'l': {"ledger"},
	'm': {"management"},
	'n': {"node"},
	'o': {"open"},
	'p': {"permissive"},
	'q': {"quantum"},
	'r': {"reachable"},
	's': {"streaming"},
	't': {"tenant"},
	'u': {"unit"},
	'v': {"virtual"},
	'w': {"wrapper"},
	// TODO: x
	'y': {"yield"},
	'z': {"zorc"},
}
